Agrega un saludo
ElsyCaro/CDMX013-data-lovers pull request #2
Opened 2022-08-18 23:28 UTC by lianlc

@ElsyCaro Revisar este cambio que agrega un saludo

2022-08-18 23:41 UTC, ElsyCaro requested changes
@lianlc Hay que cambiarlo.

2022-08-18 23:41 UTC, ElsyCaro commented on src/index.html
> +    </div>
@lianlc Faltan los cambios del botón.

2022-08-19 00:00 UTC, lianlc commented on src/index.html
> +    </div>
Listo, ya quedo resulto el conflicto!

2022-08-19 00:02 UTC, ElsyCaro commented
Listo ya revise los cambios!

2022-08-19 00:10 UTC, merged